// Seed prices for BBQ Board launch. Every entry references a shop by
// id from ./shops.js so the same price display works for any shop.
//
// Two source tiers:
//   'operator_verified' — Joel saw the price with his own eyes at that
//     store in that metro. Highest trust.
//   'chain_catalog' — from the chain's own online product listing (e.g.
//     samsclub.com Member's Mark product page). Reliable but not
//     location-specific — local warehouses may vary a few percent, but
//     it's within submission range and better than an empty board.
//
// User submissions from Firestore are labeled 'community' and merge in
// separately. Do NOT add prices you can't cite.
//
// Verified 2026-07-01.

export const SEED_PRICES = [
  {
    id: 'seed_costco_brisket_prime',
    shopId: 'costco_milwaukee_metro',
    cut: 'brisket_prime',
    pricePerLb: 5.99,
    reportedAt: '2026-07-01T00:00:00Z',
    source: 'operator_verified',
    notes: 'USDA Prime whole packer. Consistent across all Milwaukee-metro Costco warehouses.',
  },
  {
    id: 'seed_costco_brisket_choice',
    shopId: 'costco_milwaukee_metro',
    cut: 'brisket_choice',
    pricePerLb: 5.89,
    reportedAt: '2026-07-01T00:00:00Z',
    source: 'operator_verified',
    notes: 'USDA Choice whole packer. Consistent across all Milwaukee-metro Costco warehouses.',
  },
  {
    id: 'seed_walmart_brisket_choice',
    shopId: 'walmart_milwaukee_metro',
    cut: 'brisket_choice',
    pricePerLb: 5.45,
    reportedAt: '2026-07-01T00:00:00Z',
    source: 'operator_verified',
    notes: 'Whole brisket packer. Consistent across Milwaukee-area Walmart Supercenters.',
  },

  // ─── SAM'S CLUB — Member's Mark national pricing (chain catalog) ──
  // Source: samsclub.com product listings for Member's Mark Prime/Choice
  // whole brisket. National pricing is set at the chain level; local
  // warehouses may vary a few percent based on regional markdowns.
  // All Sam's Club values below verified 2026-07-01 via direct browse of
  // samsclub.com product pages (Chrome MCP) — replacing earlier WebSearch
  // data that was outdated. Member's Mark national pricing.
  ...makeSamsClubEntries('brisket_prime',  5.98, 'Member\'s Mark USDA Prime Angus Whole Brisket, vacuum-pack. samsclub.com product listing.'),
  ...makeSamsClubEntries('brisket_choice', 5.88, 'Member\'s Mark USDA Choice Angus Whole Brisket, vacuum-pack. samsclub.com product listing.'),
  ...makeSamsClubEntries('pork_shoulder',  1.98, 'Member\'s Mark Bone-In Pork Boston Butt, vacuum-pack. samsclub.com product listing.'),
  ...makeSamsClubEntries('baby_back_ribs', 3.18, 'Member\'s Mark Whole Bone-In Pork Loin Back Ribs, vacuum-pack. samsclub.com product listing.'),
  ...makeSamsClubEntries('ground_beef_80', 5.92, 'Member\'s Mark 80/20 Ground Beef. samsclub.com product listing.'),
  ...makeSamsClubEntries('chicken_breast', 2.88, 'Member\'s Mark Boneless Skinless Chicken Breast (bulk tray, final cost by weight). Operator-verified 2026-07-10.'),
  // Still open at Sam\'s Club: whole chicken, spare ribs (correct SKU
  // URL couldn\'t be resolved), and brats. Wait for user submissions
  // rather than seed with unverified numbers.

  // ─── COSTCO — Warehouse Runner tracker (crowdsourced by 500+ stores) ──
  // Source: app.warehouserunner.com, verified 2026-07-01 via live browse
  // of each item's national pricing snapshot. Numbers below are the
  // current national average across all reporting Costco warehouses;
  // retail SKUs cluster within ±$0.10 of avg for brisket/pork/chicken.
  // Milwaukee-specific brisket prices are Joel-verified above and take
  // precedence at that warehouse; national baselines for the other 5
  // Costco metros go here.
  // Brisket excludes: milwaukee = operator-verified; nashville, savannah,
  // denver, wichita, cincinnati = local prices from the Jul 13-20 scrub
  // files (explicit entries below) beat the national baseline.
  ...makeCostcoEntries('brisket_prime',   5.89, 'USDA Prime whole packer, full case. Warehouse Runner national avg (item #44856). Range $5.79-$5.99, 519 stores.', ['milwaukee', 'nashville', 'savannah', 'denver', 'cincinnati']),
  ...makeCostcoEntries('brisket_choice', 5.89, 'USDA Choice whole packer, vacuum-packed retail. Warehouse Runner national avg (item #26637). Range $4.99-$5.99, 606 stores.', ['milwaukee', 'nashville', 'savannah', 'denver', 'wichita']),
  ...makeCostcoEntries('pork_shoulder',  2.54, 'Boneless pork shoulder roast. Warehouse Runner national avg (item #62998). Range $2.49-$2.79.'),
  ...makeCostcoEntries('whole_chicken',  1.29, 'Kirkland Signature fresh whole young chicken fryer. Warehouse Runner national baseline (item #33825).'),
  ...makeCostcoEntries('ground_beef_80', 4.62, 'Kirkland Signature 80/20 ground beef, vacuum-packed. Warehouse Runner latest national avg (item #44939). Range $3.17-$4.89.'),
  ...makeCostcoEntries('baby_back_ribs', 3.73, 'Fresh pork loin back ribs. Warehouse Runner latest national avg (item #48002). Range $3.19-$4.29.'),
  ...makeCostcoEntries('spare_ribs',     3.74, 'St. Louis-style spare ribs (brisket bone removed). Warehouse Runner latest national avg (item #47002). Range $2.89-$4.29.'),
  ...makeCostcoEntries('bratwurst_fresh', 3.51, 'Kirkland Signature Bratwurst 56 oz (3.5 lb) pack, made by Johnsonville in Sheboygan Falls, WI. Warehouse Runner avg (item #1141000): $12.29/pack = $3.51/lb. Range $11.59-$13.49/pack.'),
  ...makeCostcoEntries('chicken_breast', 2.79, 'Kirkland Signature Fresh Boneless Skinless Chicken Breast. Warehouse Runner national price (item #47735). 636 stores, range $1.49-$2.99.'),

  // ─── KETTLE RANGE MEAT CO. — verified 2026-07-01 via shop.kettlerangemeats.com ──
  // Grass-fed beef + heritage pork butcher, 2 Milwaukee metro locations. Same
  // online catalog + pricing across both stores. Premium tier — expect prices
  // 2x-3x above chain baseline; that's the point of the "support local" filter.
  ...makeKettleRangeEntries('brisket_choice',  11.95, 'Grass Fed Beef Brisket, 3 lb avg. shop.kettlerangemeats.com.'),
  ...makeKettleRangeEntries('pork_shoulder',    7.95, 'Heritage Pork Shoulder (Butt) Roast. shop.kettlerangemeats.com.'),
  ...makeKettleRangeEntries('baby_back_ribs',   9.95, 'Heritage Pork Baby Back Ribs. shop.kettlerangemeats.com.'),
  ...makeKettleRangeEntries('ground_beef_80',   9.95, 'Grass Fed Ground Beef (80:20), 1 lb. shop.kettlerangemeats.com.'),
  ...makeKettleRangeEntries('whole_chicken',    5.25, 'Whole Broiler Chicken. shop.kettlerangemeats.com.'),
  ...makeKettleRangeEntries('bratwurst_fresh',  9.95, 'Milwaukee Bratwurst (4-4oz Links). shop.kettlerangemeats.com.'),

  // ─── HY-VEE — Aisles Online catalog price ──────────────────────
  // Source: hy-vee.com Aisles Online product listing for Whole Untrimmed
  // Beef Brisket. Applies to Hy-Vee footprint (Madison + KC metros).
  {
    id: 'seed_hy_vee_madison_brisket_choice',
    shopId: 'hy_vee_madison_metro',
    cut: 'brisket_choice',
    pricePerLb: 5.99,
    reportedAt: '2026-07-01T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Whole Untrimmed Beef Brisket. Hy-Vee Aisles Online catalog price.',
  },
  {
    id: 'seed_hy_vee_kc_brisket_choice',
    shopId: 'hy_vee_kc',
    cut: 'brisket_choice',
    pricePerLb: 5.99,
    reportedAt: '2026-07-01T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Whole Untrimmed Beef Brisket. Hy-Vee Aisles Online catalog price.',
  },

  // ─── LONGHORN MEAT MARKET (Austin) — verified 2026-07-02 via longhornmeatmarket.com ──
  // South Austin butcher. Shopify catalog scrape.
  {
    id: 'seed_longhorn_brisket_prime',
    shopId: 'longhorn_meat_market',
    cut: 'brisket_prime',
    pricePerLb: 10.00,
    reportedAt: '2026-07-02T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Prime Brisket, 14 lb avg @ $139.99. longhornmeatmarket.com.',
  },
  {
    id: 'seed_longhorn_pork_shoulder',
    shopId: 'longhorn_meat_market',
    cut: 'pork_shoulder',
    pricePerLb: 4.66,
    reportedAt: '2026-07-02T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Boneless Pork Butt Roast, 4.5 lb avg @ $20.99. longhornmeatmarket.com.',
  },
  {
    id: 'seed_longhorn_baby_back_ribs',
    shopId: 'longhorn_meat_market',
    cut: 'baby_back_ribs',
    pricePerLb: 10.00,
    reportedAt: '2026-07-02T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Duroc Heritage Baby Back Ribs, 3.5 lb avg @ $35. longhornmeatmarket.com.',
  },
  {
    id: 'seed_longhorn_spare_ribs',
    shopId: 'longhorn_meat_market',
    cut: 'spare_ribs',
    pricePerLb: 5.19,
    reportedAt: '2026-07-02T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Pork Spare Ribs, 5.2 lb avg @ $26.99. longhornmeatmarket.com.',
  },
  {
    id: 'seed_longhorn_ground_beef_80',
    shopId: 'longhorn_meat_market',
    cut: 'ground_beef_80',
    pricePerLb: 8.00,
    reportedAt: '2026-07-02T00:00:00Z',
    source: 'chain_catalog',
    notes: 'House Ground 80/20 Ground Beef, 1 lb @ $8. longhornmeatmarket.com.',
  },

  // ─── AUGUSTUS RANCH (Yoakum, TX) — verified 2026-07-02 via augustusranch.com ──
  // Pasture-finished beef ranch ~120mi SE of Austin. Ships statewide.
  {
    id: 'seed_augustus_ranch_brisket_choice',
    shopId: 'augustus_ranch',
    cut: 'brisket_choice',
    pricePerLb: 12.63,
    reportedAt: '2026-07-02T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Pasture-Finished Beef Brisket (point + flat), 9.5 lb avg @ $120. augustusranch.com.',
  },

  // ─── PAULINA MEAT MARKET (Chicago) — verified 2026-07-02 via paulinamarket.com ──
  {
    id: 'seed_paulina_pork_shoulder',
    shopId: 'paulina_market_chicago',
    cut: 'pork_shoulder',
    pricePerLb: 4.94,
    reportedAt: '2026-07-02T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Pork Shoulder (Skin on Bone in), 5-6 lbs. paulinamarket.com.',
  },
  {
    id: 'seed_paulina_baby_back_ribs',
    shopId: 'paulina_market_chicago',
    cut: 'baby_back_ribs',
    pricePerLb: 12.96,
    reportedAt: '2026-07-02T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Baby Back Ribs, whole rack. paulinamarket.com.',
  },
  {
    id: 'seed_paulina_spare_ribs',
    shopId: 'paulina_market_chicago',
    cut: 'spare_ribs',
    pricePerLb: 10.01,
    reportedAt: '2026-07-02T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Pork Spare Ribs (Trimmed), 3-4 lbs. paulinamarket.com.',
  },
  {
    id: 'seed_paulina_bratwurst_smoked',
    shopId: 'paulina_market_chicago',
    cut: 'bratwurst_smoked',
    pricePerLb: 9.96,
    reportedAt: '2026-07-02T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Smoked Thüringer Bratwurst, pack of 4. paulinamarket.com.',
  },
  {
    id: 'seed_paulina_whole_chicken',
    shopId: 'paulina_market_chicago',
    cut: 'whole_chicken',
    pricePerLb: 4.45,
    reportedAt: '2026-07-02T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Whole Fryer (Chicken). paulinamarket.com.',
  },
  {
    id: 'seed_paulina_whole_turkey',
    shopId: 'paulina_market_chicago',
    cut: 'whole_turkey',
    pricePerLb: 6.65,
    reportedAt: '2026-07-02T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Thanksgiving Turkey (Whole, Frozen), 10-12 lb. paulinamarket.com. Seasonal availability.',
  },

  // ─── BAVARIA SAUSAGE KITCHEN (Madison) — verified 2026-07-02 via bavariasausage.com ──
  {
    id: 'seed_bavaria_bratwurst_smoked',
    shopId: 'bavaria_sausage_madison',
    cut: 'bratwurst_smoked',
    pricePerLb: 7.58,
    reportedAt: '2026-07-02T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Bavaria\'s Berkshire Smoked Brat. bavariasausage.com.',
  },
  {
    id: 'seed_bavaria_bratwurst_fresh',
    shopId: 'bavaria_sausage_madison',
    cut: 'bratwurst_fresh',
    pricePerLb: 5.22,
    reportedAt: '2026-07-02T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Bold and Zesty Bratwurst Sampler, 8 lb box. bavariasausage.com.',
  },

  // ─── HUMPHREY'S PRIME CUT SHOPPE (Memphis) — verified 2026-07-01 via humphreysmemphis.com ──
  {
    id: 'seed_humphreys_ground_beef_80',
    shopId: 'humphreys_prime_cut_shoppe',
    cut: 'ground_beef_80',
    pricePerLb: 9.99,
    reportedAt: '2026-07-01T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Ground Beef (gourmet blend, 1 lb). humphreysmemphis.com. Fat ratio unlabeled; mapped as 80/20.',
  },

  // ─── PORTER ROAD (Nashville) — verified 2026-07-02 via porterroad.com ──
  // Pasture-raised, dry-aged. USDA grade unlabeled; quality closest to Choice.
  {
    id: 'seed_porter_road_brisket_choice',
    shopId: 'porter_road',
    cut: 'brisket_choice',
    pricePerLb: 19.01,
    reportedAt: '2026-07-02T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Brisket Flat Dry Aged, 5.5 lb avg @ $104. porterroad.com. Grade unlabeled (pasture-raised); mapped as Choice.',
  },
  {
    id: 'seed_porter_road_baby_back_ribs',
    shopId: 'porter_road',
    cut: 'baby_back_ribs',
    pricePerLb: 20.00,
    reportedAt: '2026-07-02T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Baby Back Ribs, 2 lb @ $40. porterroad.com.',
  },
  {
    id: 'seed_porter_road_spare_ribs',
    shopId: 'porter_road',
    cut: 'spare_ribs',
    pricePerLb: 9.00,
    reportedAt: '2026-07-02T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'St. Louis Ribs (trimmed spare), 2.33 lb @ $21. porterroad.com.',
  },
  {
    id: 'seed_porter_road_ground_beef_80',
    shopId: 'porter_road',
    cut: 'ground_beef_80',
    pricePerLb: 12.00,
    reportedAt: '2026-07-02T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Ground Beef Dry Aged, 1 lb. porterroad.com. Fat ratio unlabeled; mapped as 80/20.',
  },
  {
    id: 'seed_porter_road_tri_tip',
    shopId: 'porter_road',
    cut: 'tri_tip',
    pricePerLb: 43.10,
    reportedAt: '2026-07-02T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Tri-Tip Dry Aged, 1.74 lb avg @ $75. porterroad.com. Premium dry-aged pricing.',
  },

  // ─── HEXT QUALITY MEAT (Nashville) — verified 2026-07-02 via hextqualitymeat.com ──
  {
    id: 'seed_hext_brisket_choice',
    shopId: 'hext_quality_meat',
    cut: 'brisket_choice',
    pricePerLb: 10.00,
    reportedAt: '2026-07-02T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Brisket, Whole Large (13-16 lbs) @ $145. hextqualitymeat.com. Grade unlabeled; mapped as Choice.',
  },
  {
    id: 'seed_hext_ground_beef_80',
    shopId: 'hext_quality_meat',
    cut: 'ground_beef_80',
    pricePerLb: 10.00,
    reportedAt: '2026-07-02T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Ground Beef (explicitly 80/20), 1 lb. hextqualitymeat.com.',
  },
  {
    id: 'seed_hext_whole_chicken',
    shopId: 'hext_quality_meat',
    cut: 'whole_chicken',
    pricePerLb: 7.70,
    reportedAt: '2026-07-02T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Whole Chicken, 2.75-4 lb avg @ $26. hextqualitymeat.com.',
  },

  // ─── BLUE'S BUTCHER SHOP (Lockhart, TX) — verified 2026-07-07 via bluesbutchershop.com ──
  // Phelan Farms wagyu butcher in the BBQ Capital of Texas.
  {
    id: 'seed_blues_ground_beef_80',
    shopId: 'blues_butcher_shop',
    cut: 'ground_beef_80',
    pricePerLb: 11.00,
    reportedAt: '2026-07-07T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Wagyu Ground Beef 80/20, 2 lb pack @ $22. bluesbutchershop.com. Wagyu premium — higher than commodity 80/20.',
  },

  // ─── KERN MEAT COMPANY (St. Louis) — verified 2026-07-03 via kern-meat-co-inc.myshopify.com ──
  {
    id: 'seed_kern_tri_tip',
    shopId: 'kern_meat_company',
    cut: 'tri_tip',
    pricePerLb: 8.00,
    reportedAt: '2026-07-03T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Certified Hereford Beef Tri-Tip, 3.5-4 lb avg @ $31.99. kern-meat-co-inc.myshopify.com.',
  },

  // ══════════════════════════════════════════════════════════
  // JULY 20 SCRUB MERGE — prices from the Cowork daily butcher
  // scrub (data/pending-prices-*, Jul 13-20). Each entry cites
  // the shop's own listing; reportedAt is the scrub date.
  // Flagged/suspect proposals from the files were dropped:
  // Costco Wichita Prime ($4.99 suspect-low), Kroger Cincinnati
  // brisket (low-confidence snippet), Publix Nashville spare
  // ribs ($16.98/lb misparse), Von Hanson's beer brat (flavored
  // variant), plus every suspectedFalsePositives item.
  // ══════════════════════════════════════════════════════════

  // ─── SNAKE RIVER FARMS (Boise) — snakeriverfarms.com ──────
  {
    id: 'seed_snake_river_farms_brisket_choice',
    shopId: 'snake_river_farms',
    cut: 'brisket_choice',
    pricePerLb: 11.46,
    reportedAt: '2026-07-19T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Double R Ranch USDA Choice whole brisket, 11-15 lb (midpoint 13 lb). snakeriverfarms.com. Ships nationally.',
  },
  {
    id: 'seed_snake_river_farms_brisket_prime',
    shopId: 'snake_river_farms',
    cut: 'brisket_prime',
    pricePerLb: 10.90,
    reportedAt: '2026-07-18T00:00:00Z',
    source: 'chain_catalog',
    notes: 'American Wagyu SRF Black whole packer, 20-22 lb — marbling above USDA Prime. snakeriverfarms.com. Ships nationally.',
  },

  // ─── H-E-B (Austin) — heb.com, 2026-07-14 ─────────────────
  {
    id: 'seed_heb_austin_brisket_choice',
    shopId: 'heb_austin',
    cut: 'brisket_choice',
    pricePerLb: 4.46,
    reportedAt: '2026-07-14T00:00:00Z',
    source: 'chain_catalog',
    notes: 'H-E-B Beef Whole Untrimmed Brisket. heb.com. Grade unlabeled; mapped as Choice.',
  },
  {
    id: 'seed_heb_austin_spare_ribs',
    shopId: 'heb_austin',
    cut: 'spare_ribs',
    pricePerLb: 1.97,
    reportedAt: '2026-07-14T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Fresh Pork Spareribs, sale price. heb.com.',
  },
  {
    id: 'seed_heb_austin_pork_shoulder',
    shopId: 'heb_austin',
    cut: 'pork_shoulder',
    pricePerLb: 2.89,
    reportedAt: '2026-07-14T00:00:00Z',
    source: 'chain_catalog',
    notes: 'H-E-B Boneless Pork Butt Roast. heb.com.',
  },
  {
    id: 'seed_heb_austin_whole_chicken',
    shopId: 'heb_austin',
    cut: 'whole_chicken',
    pricePerLb: 1.87,
    reportedAt: '2026-07-14T00:00:00Z',
    source: 'chain_catalog',
    notes: 'H-E-B Natural Fresh Whole Chicken. heb.com.',
  },
  {
    id: 'seed_heb_austin_baby_back_ribs',
    shopId: 'heb_austin',
    cut: 'baby_back_ribs',
    pricePerLb: 4.19,
    reportedAt: '2026-07-14T00:00:00Z',
    source: 'chain_catalog',
    notes: 'H-E-B Pork Baby Back Ribs. heb.com.',
  },
  {
    id: 'seed_heb_austin_ground_beef_80',
    shopId: 'heb_austin',
    cut: 'ground_beef_80',
    pricePerLb: 5.99,
    reportedAt: '2026-07-14T00:00:00Z',
    source: 'chain_catalog',
    notes: 'H-E-B 100% Pure Ground Beef Chuck 80% Lean, value pack. heb.com.',
  },
  {
    id: 'seed_heb_austin_tri_tip',
    shopId: 'heb_austin',
    cut: 'tri_tip',
    pricePerLb: 11.99,
    reportedAt: '2026-07-14T00:00:00Z',
    source: 'chain_catalog',
    notes: 'H-E-B Boneless Beef Sirloin Tri-Tip Roast, USDA Choice. heb.com.',
  },
  {
    id: 'seed_heb_austin_chicken_breast',
    shopId: 'heb_austin',
    cut: 'chicken_breast',
    pricePerLb: 2.57,
    reportedAt: '2026-07-14T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Fresh Boneless Skinless Chicken Breasts, value pack. heb.com.',
  },
  {
    id: 'seed_central_market_austin_brisket_choice',
    shopId: 'central_market_austin',
    cut: 'brisket_choice',
    pricePerLb: 13.99,
    reportedAt: '2026-07-14T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Whole Beef Brisket Natural, Black Angus (no added hormones/antibiotics). centralmarket.com.',
  },

  // ─── NASHVILLE additions, 2026-07-14 ──────────────────────
  {
    id: 'seed_kroger_nashville_brisket_choice',
    shopId: 'kroger_nashville',
    cut: 'brisket_choice',
    pricePerLb: 4.99,
    reportedAt: '2026-07-14T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Choice whole brisket in bag, sale price (limit 1); flat cut $6.99/lb. kroger.com.',
  },
  {
    id: 'seed_publix_nashville_chicken_breast',
    shopId: 'publix_nashville',
    cut: 'chicken_breast',
    pricePerLb: 7.85,
    reportedAt: '2026-07-14T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Publix Premium boneless skinless chicken breast, USDA Grade A. publix.com delivery listing.',
  },
  {
    id: 'seed_costco_nashville_brisket_prime',
    shopId: 'costco_nashville',
    cut: 'brisket_prime',
    pricePerLb: 5.39,
    reportedAt: '2026-07-14T00:00:00Z',
    source: 'chain_catalog',
    notes: 'USDA Prime commodity brisket, full case (14 lb avg per brisket). Costco Business Center Nashville listing.',
  },
  {
    id: 'seed_costco_nashville_brisket_choice',
    shopId: 'costco_nashville',
    cut: 'brisket_choice',
    pricePerLb: 4.99,
    reportedAt: '2026-07-14T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Kirkland Signature vacuum-packed USDA Choice whole brisket. Costco Nashville same-day listing.',
  },

  // ─── MEAT PEOPLE BUTCHER (Madison) — meatpeoplebutcher.com, 2026-07-18 ──
  {
    id: 'seed_meat_people_brisket_choice',
    shopId: 'meat_people_madison',
    cut: 'brisket_choice',
    pricePerLb: 11.00,
    reportedAt: '2026-07-18T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Whole Brisket (flat + point), local-farm whole-animal butcher. meatpeoplebutcher.com. Ungraded; mapped as Choice.',
  },
  {
    id: 'seed_meat_people_tri_tip',
    shopId: 'meat_people_madison',
    cut: 'tri_tip',
    pricePerLb: 16.00,
    reportedAt: '2026-07-18T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Tri-tip, published price list. meatpeoplebutcher.com.',
  },
  {
    id: 'seed_meat_people_spare_ribs',
    shopId: 'meat_people_madison',
    cut: 'spare_ribs',
    pricePerLb: 8.00,
    reportedAt: '2026-07-18T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Pork spare ribs (St. Louis trim not specified). meatpeoplebutcher.com.',
  },
  {
    id: 'seed_meat_people_pork_shoulder',
    shopId: 'meat_people_madison',
    cut: 'pork_shoulder',
    pricePerLb: 8.00,
    reportedAt: '2026-07-18T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Bone-in pork shoulder; boneless $9/lb. meatpeoplebutcher.com.',
  },
  {
    id: 'seed_meat_people_whole_chicken',
    shopId: 'meat_people_madison',
    cut: 'whole_chicken',
    pricePerLb: 6.50,
    reportedAt: '2026-07-18T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Whole pastured chicken, published price list. meatpeoplebutcher.com.',
  },

  // ─── MEMPHIS additions, 2026-07-18 ────────────────────────
  {
    id: 'seed_kroger_memphis_brisket_choice',
    shopId: 'kroger_memphis',
    cut: 'brisket_choice',
    pricePerLb: 4.99,
    reportedAt: '2026-07-18T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Choice whole brisket in bag, sale price (limit 1); flat cut $6.99/lb. kroger.com.',
  },
  {
    id: 'seed_kroger_memphis_pork_shoulder',
    shopId: 'kroger_memphis',
    cut: 'pork_shoulder',
    pricePerLb: 2.59,
    reportedAt: '2026-07-18T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Kroger Fresh Natural Pork Shoulder Butt, bone-in. kroger.com.',
  },
  {
    id: 'seed_ramons_ground_beef_80',
    shopId: 'ramons_meat_market_memphis',
    cut: 'ground_beef_80',
    pricePerLb: 5.00,
    reportedAt: '2026-07-18T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Ground Beef, $5.00/lb explicit on listing. ramonsmeatmarket.com. Blend unlabeled; mapped as 80/20.',
  },

  // ─── FORT WORTH (dallas_metro) additions, 2026-07-19 ──────
  {
    id: 'seed_heb_fort_worth_brisket_choice',
    shopId: 'heb_fort_worth_area',
    cut: 'brisket_choice',
    pricePerLb: 4.46,
    reportedAt: '2026-07-19T00:00:00Z',
    source: 'chain_catalog',
    notes: 'H-E-B Beef Whole Untrimmed Brisket. heb.com. Grade unlabeled; mapped as Choice.',
  },
  {
    id: 'seed_wild_fork_fort_worth_brisket_choice',
    shopId: 'wild_fork_fort_worth',
    cut: 'brisket_choice',
    pricePerLb: 3.98,
    reportedAt: '2026-07-19T00:00:00Z',
    source: 'chain_catalog',
    notes: 'USDA Choice whole brisket, ~14.25 lb. wildforkfoods.com listing.',
  },
  {
    id: 'seed_country_meat_market_fw_ground_beef_80',
    shopId: 'country_meat_market_fort_worth',
    cut: 'ground_beef_80',
    pricePerLb: 6.99,
    reportedAt: '2026-07-19T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Ground Chuck (typically ~80/20). countrymeatmarket.com.',
  },
  {
    id: 'seed_burgundys_pork_shoulder',
    shopId: 'burgundys_local_fort_worth',
    cut: 'pork_shoulder',
    pricePerLb: 11.00,
    reportedAt: '2026-07-19T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Pasture-raised Pork Shoulder Roast, 3 lb. burgundypasturebeef.com.',
  },
  {
    id: 'seed_burgundys_bratwurst_fresh',
    shopId: 'burgundys_local_fort_worth',
    cut: 'bratwurst_fresh',
    pricePerLb: 13.19,
    reportedAt: '2026-07-19T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Pork bratwurst links, raw, natural casing (4 links / 1.25 lb). burgundypasturebeef.com.',
  },
  {
    id: 'seed_burgundys_whole_chicken',
    shopId: 'burgundys_local_fort_worth',
    cut: 'whole_chicken',
    pricePerLb: 10.00,
    reportedAt: '2026-07-19T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Pasture-raised whole chicken, 2.8-3 lb. burgundypasturebeef.com.',
  },

  // ─── LITTLE ROCK, 2026-07-13 ──────────────────────────────
  {
    id: 'seed_kroger_little_rock_pork_shoulder',
    shopId: 'kroger_little_rock',
    cut: 'pork_shoulder',
    pricePerLb: 2.59,
    reportedAt: '2026-07-13T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Kroger Fresh Natural Pork Shoulder Butt, bone-in. kroger.com.',
  },

  // ─── NEW ORLEANS, 2026-07-13 ──────────────────────────────
  {
    id: 'seed_winn_dixie_spare_ribs',
    shopId: 'winn_dixie_new_orleans',
    cut: 'spare_ribs',
    pricePerLb: 2.88,
    reportedAt: '2026-07-13T00:00:00Z',
    source: 'chain_catalog',
    notes: 'St. Louis-style pork spareribs, weekly-ad price.',
  },
  {
    id: 'seed_rouses_pork_shoulder',
    shopId: 'rouses_new_orleans',
    cut: 'pork_shoulder',
    pricePerLb: 2.49,
    reportedAt: '2026-07-13T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Boneless Boston Butt Roast. rouses.com online ordering.',
  },
  {
    id: 'seed_aldi_new_orleans_spare_ribs',
    shopId: 'aldi_new_orleans',
    cut: 'spare_ribs',
    pricePerLb: 1.99,
    reportedAt: '2026-07-13T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Fresh pork spareribs, weekly-ad price.',
  },
  {
    id: 'seed_aldi_new_orleans_ground_beef_80',
    shopId: 'aldi_new_orleans',
    cut: 'ground_beef_80',
    pricePerLb: 4.99,
    reportedAt: '2026-07-13T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Fresh 80% lean ground beef patties, weekly-ad price.',
  },

  // ─── SAVANNAH, 2026-07-13 ─────────────────────────────────
  {
    id: 'seed_costco_savannah_brisket_choice',
    shopId: 'costco_savannah',
    cut: 'brisket_choice',
    pricePerLb: 5.49,
    reportedAt: '2026-07-13T00:00:00Z',
    source: 'chain_catalog',
    notes: 'USDA Choice whole brisket cryovac, ~14 lb avg. Costco Business Delivery Savannah listing.',
  },
  {
    id: 'seed_costco_savannah_brisket_prime',
    shopId: 'costco_savannah',
    cut: 'brisket_prime',
    pricePerLb: 5.69,
    reportedAt: '2026-07-13T00:00:00Z',
    source: 'chain_catalog',
    notes: 'USDA Prime commodity brisket, ~14 lb avg. Costco Business Delivery Savannah listing.',
  },
  {
    id: 'seed_publix_savannah_brisket_choice',
    shopId: 'publix_savannah',
    cut: 'brisket_choice',
    pricePerLb: 6.30,
    reportedAt: '2026-07-13T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Publix USDA Choice whole brisket with point, in the bag. publix.com delivery listing.',
  },
  {
    id: 'seed_publix_savannah_chicken_breast',
    shopId: 'publix_savannah',
    cut: 'chicken_breast',
    pricePerLb: 7.85,
    reportedAt: '2026-07-13T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Publix Premium boneless skinless chicken breast, USDA Grade A. publix.com delivery listing.',
  },

  // ─── DENVER, 2026-07-15 ───────────────────────────────────
  {
    id: 'seed_rugby_scott_brisket_prime',
    shopId: 'rugby_scott_ranch',
    cut: 'brisket_prime',
    pricePerLb: 9.95,
    reportedAt: '2026-07-15T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'American Wagyu Silver brisket, 18-20 lb avg. shop.rugbyscott.com. Wagyu marbling; mapped as Prime.',
  },
  {
    id: 'seed_costco_denver_brisket_choice',
    shopId: 'costco_denver',
    cut: 'brisket_choice',
    pricePerLb: 4.99,
    reportedAt: '2026-07-15T00:00:00Z',
    source: 'chain_catalog',
    notes: 'USDA Choice whole brisket vacuum-packed, 16 lb avg (item #26637). Warehouse Runner Denver-metro price.',
  },
  {
    id: 'seed_costco_denver_brisket_prime',
    shopId: 'costco_denver',
    cut: 'brisket_prime',
    pricePerLb: 5.79,
    reportedAt: '2026-07-15T00:00:00Z',
    source: 'chain_catalog',
    notes: 'USDA Prime commodity brisket, full case (item #44856). Warehouse Runner Denver-metro price.',
  },

  // ─── JACKSONVILLE — PREMIER MEATS, 2026-07-16 ─────────────
  {
    id: 'seed_premier_meats_brisket_choice',
    shopId: 'premier_meats_jacksonville',
    cut: 'brisket_choice',
    pricePerLb: 17.99,
    reportedAt: '2026-07-16T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Brisket, sold by the lb. premiermeatfl.com. Grade unlabeled; mapped as Choice.',
  },
  {
    id: 'seed_premier_meats_ground_beef_80',
    shopId: 'premier_meats_jacksonville',
    cut: 'ground_beef_80',
    pricePerLb: 6.49,
    reportedAt: '2026-07-16T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Ground Beef. premiermeatfl.com. Ratio unlabeled; mapped as 80/20.',
  },
  {
    id: 'seed_premier_meats_spare_ribs',
    shopId: 'premier_meats_jacksonville',
    cut: 'spare_ribs',
    pricePerLb: 2.99,
    reportedAt: '2026-07-16T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Pork spare ribs, St. Louis cut. premiermeatfl.com.',
  },
  {
    id: 'seed_premier_meats_baby_back_ribs',
    shopId: 'premier_meats_jacksonville',
    cut: 'baby_back_ribs',
    pricePerLb: 4.49,
    reportedAt: '2026-07-16T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Baby back ribs. premiermeatfl.com.',
  },
  {
    id: 'seed_premier_meats_whole_chicken',
    shopId: 'premier_meats_jacksonville',
    cut: 'whole_chicken',
    pricePerLb: 2.89,
    reportedAt: '2026-07-16T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Whole chicken. premiermeatfl.com.',
  },
  {
    id: 'seed_premier_meats_chicken_breast',
    shopId: 'premier_meats_jacksonville',
    cut: 'chicken_breast',
    pricePerLb: 3.99,
    reportedAt: '2026-07-16T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Halal raw chicken breast. premiermeatfl.com.',
  },

  // ─── PHOENIX — ARCADIA MEAT MARKET, 2026-07-17 ────────────
  {
    id: 'seed_arcadia_brisket_choice',
    shopId: 'arcadia_meat_market_phoenix',
    cut: 'brisket_choice',
    pricePerLb: 10.00,
    reportedAt: '2026-07-17T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Arizona free-range 100% grass-fed brisket. arcadiameatmarket.com. Ungraded; mapped as Choice.',
  },
  {
    id: 'seed_arcadia_tri_tip',
    shopId: 'arcadia_meat_market_phoenix',
    cut: 'tri_tip',
    pricePerLb: 20.00,
    reportedAt: '2026-07-17T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Arizona free-range grass-fed tri-tip. arcadiameatmarket.com.',
  },
  {
    id: 'seed_arcadia_pork_shoulder',
    shopId: 'arcadia_meat_market_phoenix',
    cut: 'pork_shoulder',
    pricePerLb: 7.00,
    reportedAt: '2026-07-17T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Chiricahua pasture-raised bone-in shoulder roast; boneless $8/lb. arcadiameatmarket.com.',
  },
  {
    id: 'seed_arcadia_spare_ribs',
    shopId: 'arcadia_meat_market_phoenix',
    cut: 'spare_ribs',
    pricePerLb: 8.00,
    reportedAt: '2026-07-17T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Chiricahua pasture-raised pork spare ribs. arcadiameatmarket.com.',
  },
  {
    id: 'seed_arcadia_bratwurst_fresh',
    shopId: 'arcadia_meat_market_phoenix',
    cut: 'bratwurst_fresh',
    pricePerLb: 9.00,
    reportedAt: '2026-07-17T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Chiricahua pasture-raised pork bratwurst. arcadiameatmarket.com.',
  },
  {
    id: 'seed_arcadia_whole_chicken',
    shopId: 'arcadia_meat_market_phoenix',
    cut: 'whole_chicken',
    pricePerLb: 7.00,
    reportedAt: '2026-07-17T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Top Knot Farms pasture-raised whole chicken. arcadiameatmarket.com.',
  },
  {
    id: 'seed_arcadia_chicken_breast',
    shopId: 'arcadia_meat_market_phoenix',
    cut: 'chicken_breast',
    pricePerLb: 10.00,
    reportedAt: '2026-07-17T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Top Knot Farms bone-in breasts (boneless not listed). arcadiameatmarket.com.',
  },

  // ─── WICHITA, 2026-07-16 ──────────────────────────────────
  {
    id: 'seed_phils_farm_brisket_choice',
    shopId: 'phils_farm_butchery',
    cut: 'brisket_choice',
    pricePerLb: 13.05,
    reportedAt: '2026-07-16T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Beef brisket, published price sheet (Nov 2025). phils.farm. Ungraded; mapped as Choice.',
  },
  {
    id: 'seed_phils_farm_tri_tip',
    shopId: 'phils_farm_butchery',
    cut: 'tri_tip',
    pricePerLb: 15.60,
    reportedAt: '2026-07-16T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Tri-tip, published price sheet. phils.farm.',
  },
  {
    id: 'seed_phils_farm_pork_shoulder',
    shopId: 'phils_farm_butchery',
    cut: 'pork_shoulder',
    pricePerLb: 7.35,
    reportedAt: '2026-07-16T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Bone-in pork shoulder/butt roast, published price sheet. phils.farm.',
  },
  {
    id: 'seed_phils_farm_spare_ribs',
    shopId: 'phils_farm_butchery',
    cut: 'spare_ribs',
    pricePerLb: 5.50,
    reportedAt: '2026-07-16T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Pork spare ribs (trim style unspecified), published price sheet. phils.farm.',
  },
  {
    id: 'seed_phils_farm_bratwurst_fresh',
    shopId: 'phils_farm_butchery',
    cut: 'bratwurst_fresh',
    pricePerLb: 8.05,
    reportedAt: '2026-07-16T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Classic Brat (cheapest fresh brat; specialty brats $8.35-$8.95). phils.farm.',
  },
  {
    id: 'seed_phils_farm_whole_chicken',
    shopId: 'phils_farm_butchery',
    cut: 'whole_chicken',
    pricePerLb: 5.65,
    reportedAt: '2026-07-16T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Whole pasture-raised chicken, published price sheet. phils.farm.',
  },
  {
    id: 'seed_phils_farm_chicken_breast',
    shopId: 'phils_farm_butchery',
    cut: 'chicken_breast',
    pricePerLb: 11.15,
    reportedAt: '2026-07-16T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Boneless skinless breast, raw. phils.farm.',
  },
  {
    id: 'seed_phils_farm_whole_turkey',
    shopId: 'phils_farm_butchery',
    cut: 'whole_turkey',
    pricePerLb: 5.65,
    reportedAt: '2026-07-16T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Whole turkey, published price sheet. phils.farm.',
  },
  {
    id: 'seed_dillons_wichita_brisket_choice',
    shopId: 'dillons_wichita',
    cut: 'brisket_choice',
    pricePerLb: 5.99,
    reportedAt: '2026-07-16T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Choice beef brisket, sold whole in the bag. dillons.com.',
  },
  {
    id: 'seed_dillons_wichita_pork_shoulder',
    shopId: 'dillons_wichita',
    cut: 'pork_shoulder',
    pricePerLb: 4.49,
    reportedAt: '2026-07-16T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Kroger Fresh Natural Pork Shoulder Butt, bone-in. dillons.com.',
  },
  {
    id: 'seed_dillons_wichita_spare_ribs',
    shopId: 'dillons_wichita',
    cut: 'spare_ribs',
    pricePerLb: 4.49,
    reportedAt: '2026-07-16T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Kroger pork spareribs, whole (not St. Louis trimmed). dillons.com.',
  },
  {
    id: 'seed_costco_wichita_brisket_choice',
    shopId: 'costco_wichita',
    cut: 'brisket_choice',
    pricePerLb: 4.99,
    reportedAt: '2026-07-16T00:00:00Z',
    source: 'chain_catalog',
    notes: 'USDA Choice whole brisket vacuum-packed (item #26637), down from $5.99. Warehouse Runner Wichita price.',
  },

  // ─── TWIN CITIES, 2026-07-18 ──────────────────────────────
  {
    id: 'seed_lunds_byerlys_brisket_choice',
    shopId: 'lunds_byerlys_minneapolis',
    cut: 'brisket_choice',
    pricePerLb: 16.99,
    reportedAt: '2026-07-18T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Premium Choice boneless brisket, trimmed 3.75 lb avg (not a full packer). lundsandbyerlys.com.',
  },
  {
    id: 'seed_lunds_byerlys_tri_tip',
    shopId: 'lunds_byerlys_minneapolis',
    cut: 'tri_tip',
    pricePerLb: 19.99,
    reportedAt: '2026-07-18T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Premium Choice tri-tip roast, 1.75 lb avg. lundsandbyerlys.com.',
  },
  {
    id: 'seed_hyvee_twin_cities_pork_shoulder',
    shopId: 'hyvee_twin_cities',
    cut: 'pork_shoulder',
    pricePerLb: 1.99,
    reportedAt: '2026-07-18T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Fresh pork shoulder blade Boston butt. hy-vee.com Aisles Online; local stores may vary.',
  },
  {
    id: 'seed_kramarczuks_bratwurst_fresh',
    shopId: 'kramarczuks_minneapolis',
    cut: 'bratwurst_fresh',
    pricePerLb: 7.50,
    reportedAt: '2026-07-18T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Fresh uncooked bratwurst, 4 links/~1 lb, natural hog casing. shop.kramarczuks.com.',
  },
  {
    id: 'seed_kramarczuks_bratwurst_smoked',
    shopId: 'kramarczuks_minneapolis',
    cut: 'bratwurst_smoked',
    pricePerLb: 8.00,
    reportedAt: '2026-07-18T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Regular smoked bratwurst, 4 links/~1 lb. shop.kramarczuks.com.',
  },
  {
    id: 'seed_von_hansons_bratwurst_smoked',
    shopId: 'von_hansons_twin_cities',
    cut: 'bratwurst_smoked',
    pricePerLb: 12.99,
    reportedAt: '2026-07-18T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Fully cooked smoked brats, 1 lb pack. shopvonhansons.com.',
  },

  // ─── OMAHA, 2026-07-17 ────────────────────────────────────
  {
    id: 'seed_rustic_cuts_ground_beef_80',
    shopId: 'rustic_cuts',
    cut: 'ground_beef_80',
    pricePerLb: 6.50,
    reportedAt: '2026-07-17T00:00:00Z',
    source: 'shopify_catalog',
    notes: '80/20 ground beef, 20 lb box @ $129.99. rusticcutsmeat.com.',
  },
  {
    id: 'seed_rustic_cuts_chicken_breast',
    shopId: 'rustic_cuts',
    cut: 'chicken_breast',
    pricePerLb: 6.00,
    reportedAt: '2026-07-17T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Premium chicken breast, 10 lb box. rusticcutsmeat.com.',
  },
  {
    id: 'seed_frank_stoysich_bratwurst_fresh',
    shopId: 'frank_stoysich_meats',
    cut: 'bratwurst_fresh',
    pricePerLb: 7.00,
    reportedAt: '2026-07-17T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Fresh bratwurst, 4 links per lb, sold by the pound. stoysichonline.com.',
  },
  {
    id: 'seed_hy_vee_omaha_pork_shoulder',
    shopId: 'hy_vee_omaha',
    cut: 'pork_shoulder',
    pricePerLb: 1.99,
    reportedAt: '2026-07-17T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Fresh pork shoulder blade Boston butt. hy-vee.com Aisles Online; local stores may vary.',
  },
  {
    id: 'seed_hy_vee_omaha_whole_chicken',
    shopId: 'hy_vee_omaha',
    cut: 'whole_chicken',
    pricePerLb: 2.28,
    reportedAt: '2026-07-17T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Hy-Vee fresh young whole chicken. hy-vee.com Aisles Online.',
  },
  {
    id: 'seed_hy_vee_omaha_brisket_choice',
    shopId: 'hy_vee_omaha',
    cut: 'brisket_choice',
    pricePerLb: 5.77,
    reportedAt: '2026-07-17T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Whole untrimmed beef brisket. hy-vee.com Aisles Online. Grade unlabeled; mapped as Choice.',
  },

  // ─── CINCINNATI, 2026-07-19 ───────────────────────────────
  {
    id: 'seed_costco_cincinnati_brisket_prime',
    shopId: 'costco_cincinnati',
    cut: 'brisket_prime',
    pricePerLb: 5.99,
    reportedAt: '2026-07-19T00:00:00Z',
    source: 'chain_catalog',
    notes: 'USDA Prime whole brisket vacuum-packed (item #44816), ~14-18 lb packer. Warehouse Runner Cincinnati price.',
  },
  {
    id: 'seed_eckerlin_tri_tip',
    shopId: 'eckerlin_meats',
    cut: 'tri_tip',
    pricePerLb: 15.20,
    reportedAt: '2026-07-19T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Tri-tip, ~2.5 lb each; final price by weight. shop.findlaymarket.org.',
  },
  {
    id: 'seed_eckerlin_chicken_breast',
    shopId: 'eckerlin_meats',
    cut: 'chicken_breast',
    pricePerLb: 8.75,
    reportedAt: '2026-07-19T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Gerber Amish chicken breast, raw fresh. shop.findlaymarket.org.',
  },
  {
    id: 'seed_eckerlin_bratwurst_fresh',
    shopId: 'eckerlin_meats',
    cut: 'bratwurst_fresh',
    pricePerLb: 7.50,
    reportedAt: '2026-07-19T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'House brats, 1 lb (fresh; smoked listed separately). shop.findlaymarket.org.',
  },
  {
    id: 'seed_eckerlin_ground_beef_80',
    shopId: 'eckerlin_meats',
    cut: 'ground_beef_80',
    pricePerLb: 6.99,
    reportedAt: '2026-07-19T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'House blend ground chuck (typically ~80/20). shop.findlaymarket.org.',
  },
  {
    id: 'seed_country_meat_co_baby_back_ribs',
    shopId: 'country_meat_co',
    cut: 'baby_back_ribs',
    pricePerLb: 7.29,
    reportedAt: '2026-07-19T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Baby back ribs, 2.5 lb rack. shop.findlaymarket.org.',
  },
  {
    id: 'seed_country_meat_co_whole_chicken',
    shopId: 'country_meat_co',
    cut: 'whole_chicken',
    pricePerLb: 4.07,
    reportedAt: '2026-07-19T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Fresh Amish fryer chicken, ~3.5 lb; final price by weight. shop.findlaymarket.org.',
  },
  {
    id: 'seed_country_meat_co_chicken_breast',
    shopId: 'country_meat_co',
    cut: 'chicken_breast',
    pricePerLb: 12.98,
    reportedAt: '2026-07-19T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Boneless chicken breasts, sold per ~0.5 lb breast. shop.findlaymarket.org.',
  },

  // ─── INDIANAPOLIS, 2026-07-19 ─────────────────────────────
  {
    id: 'seed_meijer_indy_whole_chicken',
    shopId: 'meijer_indianapolis',
    cut: 'whole_chicken',
    pricePerLb: 2.99,
    reportedAt: '2026-07-19T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Meijer all-natural bone-in whole chicken, ~4 lb; promo $2.49/lb on larger birds. meijer.com.',
  },
  {
    id: 'seed_meijer_indy_chicken_breast',
    shopId: 'meijer_indianapolis',
    cut: 'chicken_breast',
    pricePerLb: 4.19,
    reportedAt: '2026-07-19T00:00:00Z',
    source: 'chain_catalog',
    notes: 'Meijer boneless skinless breasts, family pack ($4.19-$4.99 by pack size). meijer.com.',
  },
  {
    id: 'seed_kincaids_whole_chicken',
    shopId: 'kincaids_meat_market',
    cut: 'whole_chicken',
    pricePerLb: 6.00,
    reportedAt: '2026-07-19T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Gerber Farms whole chicken, ~3.5 lb Amish farm bird. kincaidsmeatmarket.com.',
  },
  {
    id: 'seed_kincaids_chicken_breast',
    shopId: 'kincaids_meat_market',
    cut: 'chicken_breast',
    pricePerLb: 9.99,
    reportedAt: '2026-07-19T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Gerber Farms boneless skinless breasts, four 6 oz pack. kincaidsmeatmarket.com.',
  },
  {
    id: 'seed_kincaids_ground_beef_80',
    shopId: 'kincaids_meat_market',
    cut: 'ground_beef_80',
    pricePerLb: 8.31,
    reportedAt: '2026-07-19T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'USDA Prime Angus regular ground beef. kincaidsmeatmarket.com. Ratio unlabeled; mapped as 80/20.',
  },
  {
    id: 'seed_kincaids_whole_turkey',
    shopId: 'kincaids_meat_market',
    cut: 'whole_turkey',
    pricePerLb: 5.99,
    reportedAt: '2026-07-19T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Rosebud whole turkey, 8-12 lb variant. kincaidsmeatmarket.com.',
  },
  {
    id: 'seed_goose_spare_ribs',
    shopId: 'goose_the_market',
    cut: 'spare_ribs',
    pricePerLb: 9.00,
    reportedAt: '2026-07-19T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Gunthorp Farms pork spare ribs, per lb via Mercato listing.',
  },
  {
    id: 'seed_goose_whole_chicken',
    shopId: 'goose_the_market',
    cut: 'whole_chicken',
    pricePerLb: 8.00,
    reportedAt: '2026-07-19T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Whole chicken, per lb via Mercato listing.',
  },
  {
    id: 'seed_goose_chicken_breast',
    shopId: 'goose_the_market',
    cut: 'chicken_breast',
    pricePerLb: 16.96,
    reportedAt: '2026-07-19T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Skinless chicken breast, per lb via Mercato listing (premium shop; Mercato pricing).',
  },

  // ─── PITTSBURGH, 2026-07-20 ───────────────────────────────
  {
    id: 'seed_prime_butcher_brisket_choice',
    shopId: 'the_prime_butcher',
    cut: 'brisket_choice',
    pricePerLb: 16.36,
    reportedAt: '2026-07-20T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'USDA Choice Midwest Angus single brisket flat, 5-6 lb avg. theprimebutcherpgh.com.',
  },
  {
    id: 'seed_weiss_brisket_choice',
    shopId: 'weiss_meats',
    cut: 'brisket_choice',
    pricePerLb: 7.59,
    reportedAt: '2026-07-20T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Choice brisket, sale price (regular $11.99/lb). weissmeats.com.',
  },
  {
    id: 'seed_weiss_ground_beef_80',
    shopId: 'weiss_meats',
    cut: 'ground_beef_80',
    pricePerLb: 4.99,
    reportedAt: '2026-07-20T00:00:00Z',
    source: 'shopify_catalog',
    notes: '80/20 lean ground beef, sale price (regular $6.49/lb). weissmeats.com.',
  },
  {
    id: 'seed_weiss_tri_tip',
    shopId: 'weiss_meats',
    cut: 'tri_tip',
    pricePerLb: 8.99,
    reportedAt: '2026-07-20T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Angus tri-tips, sale price (regular $11.99/lb). weissmeats.com.',
  },
  {
    id: 'seed_weiss_baby_back_ribs',
    shopId: 'weiss_meats',
    cut: 'baby_back_ribs',
    pricePerLb: 3.89,
    reportedAt: '2026-07-20T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Baby back ribs, sale price (regular $4.29/lb). weissmeats.com.',
  },
  {
    id: 'seed_weiss_pork_shoulder',
    shopId: 'weiss_meats',
    cut: 'pork_shoulder',
    pricePerLb: 2.39,
    reportedAt: '2026-07-20T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Bone-in pork butt, sale price (regular $4.49/lb); boneless $2.69/lb. weissmeats.com.',
  },
  {
    id: 'seed_weiss_spare_ribs',
    shopId: 'weiss_meats',
    cut: 'spare_ribs',
    pricePerLb: 3.49,
    reportedAt: '2026-07-20T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Pork spare ribs, sale price (regular $6.89/lb). weissmeats.com.',
  },
  {
    id: 'seed_weiss_whole_chicken',
    shopId: 'weiss_meats',
    cut: 'whole_chicken',
    pricePerLb: 1.99,
    reportedAt: '2026-07-20T00:00:00Z',
    source: 'shopify_catalog',
    notes: 'Whole chicken, sale price (regular $3.79/lb). weissmeats.com.',
  },
  {
    id: 'seed_weiss_chicken_breast',
    shopId: 'weiss_meats',
    cut: 'chicken_breast',
    pricePerLb: 2.65,
    reportedAt: '2026-07-20T00:00:00Z',
    source: 'shopify_catalog',
    notes: '99% fat-free boneless breasts, 10 lb box sale (regular $44.99/box). weissmeats.com.',
  },
];

// Sam's Club Prime and Choice brisket carry the same national pricing
// across every warehouse. Apply to every metro that has a Sam's Club
// entry in shops.js so the board shows a price at every one.
function makeSamsClubEntries(cut, pricePerLb, note) {
  const shopIds = [
    'sams_club_milwaukee_metro',
    'sams_club_madison_metro',
    'sams_club_green_bay',
    'sams_club_appleton',
    'sams_club_chicago',
    'sams_club_kc',
    'sams_club_memphis',
    'sams_club_nashville',
    'sams_club_st_louis',
    'sams_club_dallas',
    'sams_club_houston',
    'sams_club_san_antonio',
    'sams_club_birmingham',
    'sams_club_boise',
    'sams_club_lexington',
    'sams_club_greenville',
    'sams_club_owensboro',
    'sams_club_lockhart',
    'sams_club_atlanta',
    'sams_club_louisville',
    'sams_club_charlotte',
    'sams_club_raleigh',
    'sams_club_columbia',
    'sams_club_tuscaloosa',
    'sams_club_oklahoma_city',
    'sams_club_tulsa',
    'sams_club_austin',
    'sams_club_little_rock',
    'sams_club_new_orleans',
    'sams_club_savannah',
    'sams_club_denver',
    'sams_club_jacksonville',
    'sams_club_phoenix',
    'sams_club_wichita',
    'sams_club_twin_cities',
    'sams_club_omaha',
    'sams_club_cincinnati',
    'sams_club_indianapolis',
    'sams_club_pittsburgh',
  ];
  return shopIds.map(shopId => ({
    id: `seed_${shopId}_${cut}`,
    shopId,
    cut,
    pricePerLb,
    reportedAt: '2026-07-01T00:00:00Z',
    source: 'chain_catalog',
    notes: note,
  }));
}

// Kettle Range operates 2 Milwaukee-metro locations sharing the same
// online catalog. Both get the same seed price per cut.
function makeKettleRangeEntries(cut, pricePerLb, note) {
  return ['kettle_range_milwaukee', 'kettle_range_elm_grove'].map(shopId => ({
    id: `seed_${shopId}_${cut}`,
    shopId, cut, pricePerLb,
    reportedAt: '2026-07-01T00:00:00Z',
    source: 'chain_catalog',
    notes: note,
  }));
}

// Costco Kirkland Signature and Swift-brand cuts are priced at the chain
// level too. excludeMetros lets us skip metros where Joel has verified
// operator data — his ground truth wins over national baselines.
function makeCostcoEntries(cut, pricePerLb, note, excludeMetros = []) {
  const shopIds = [
    'costco_milwaukee_metro',
    'costco_madison_metro',
    'costco_green_bay',
    'costco_appleton',
    'costco_chicago',
    'costco_kc',
    'costco_memphis',
    'costco_nashville',
    'costco_st_louis',
    'costco_dallas',
    'costco_houston',
    'costco_san_antonio',
    'costco_birmingham',
    'costco_boise',
    'costco_lexington',
    'costco_greenville',
    'costco_owensboro',
    'costco_lockhart',
    'costco_atlanta',
    'costco_louisville',
    'costco_charlotte',
    'costco_raleigh',
    'costco_columbia',
    'costco_tuscaloosa',
    'costco_oklahoma_city',
    'costco_tulsa',
    'costco_austin',
    'costco_little_rock',
    'costco_new_orleans',
    'costco_savannah',
    'costco_denver',
    'costco_jacksonville',
    'costco_phoenix',
    'costco_wichita',
    'costco_twin_cities',
    'costco_omaha',
    'costco_cincinnati',
    'costco_indianapolis',
    'costco_pittsburgh',
  ];
  const kept = shopIds.filter(id => !excludeMetros.some(m => id.includes(m)));
  return kept.map(shopId => ({
    id: `seed_${shopId}_${cut}`,
    shopId,
    cut,
    pricePerLb,
    reportedAt: '2026-07-01T00:00:00Z',
    source: 'chain_catalog',
    notes: note,
  }));
}
