/* ── Sample data for first-time users ── */

export const SAMPLE_REVIEW = {
  id: '__example_review__',
  _isExample: true,
  restaurant: "Smokin' Joe's BBQ",
  date: '2026-05-17',
  location: 'Kansas City, MO',
  trip: 'KC Weekend',
  meats: ['Brisket', 'Burnt Ends', 'Ribs'],
  meatOther: '',
  sides: ['Mac & Cheese', 'Beans', 'Coleslaw'],
  sideOther: '',
  dessert: 'Banana pudding',
  scores: {
    appearance: 8,
    taste: 7,
    tenderness: 8,
    smoke: 7,
    sides: 6,
    sauce: 7,
    portions: 8,
    service: 7,
    cleanliness: 6,
    amenities: 5,
  },
  sauceDep: 'No — meat stood on its own',
  wouldReturn: 'Absolutely',
  notes: '',
  notesLog: [
    '2026-05-17: Brisket had a perfect smoke ring. Bark was solid.',
    '2026-05-17: Burnt ends were crispy on the outside, melt-in-your-mouth inside.',
    '2026-05-17: Mac and cheese was above average. Beans were standard.',
  ],
  price: '47',
  priceSplit: '2',
  googleReviewUrl: '',
  photo: null,
  photos: [],
  friends: [],
  lastEdited: null,
};

// Sample friend cooks — render in Cook Compare alongside the user's own
// cooks until real friend cook sync lands (v2.1). Each one is marked
// _isExample so the UI can badge it accordingly. Picked across three
// meats with two fake friend names so the recency feed feels alive
// and the bracket layout has real material to compare against.
export const SAMPLE_FRIEND_COOKS = [
  {
    id: '__example_friend_cook_1__',
    _isExample: true,
    userName: 'Brother Brian',
    name: 'Memorial Day Brisket',
    date: '2026-05-25',
    meatType: 'Brisket',
    cut: 'Whole packer, prime',
    weight: '15',
    rub: 'SPG — equal parts salt, pepper, garlic',
    woodType: ['Hickory', 'Oak'],
    smokerType: 'Pit Boss Pro Series',
    fuelSource: 'Pellets',
    cookTemp: '225',
    wrapMethod: 'Butcher paper',
    wrapTemp: '165',
    targetInternalTemp: '201',
    cookTimeHours: '14',
    cookTimeMinutes: '0',
    restTime: '120',
    weatherTemp: '68',
    weatherHumidity: '40%',
    rating: 8,
    tags: ['weekend'],
    photos: [],
    notesLog: [],
  },
  {
    id: '__example_friend_cook_2__',
    _isExample: true,
    userName: 'Dad',
    name: 'Tailgate Brisket',
    date: '2026-05-18',
    meatType: 'Brisket',
    cut: 'Flat only, choice',
    weight: '9',
    rub: 'Texas style — coarse pepper + salt',
    woodType: ['Post oak'],
    smokerType: 'Offset stick burner',
    fuelSource: 'Wood',
    cookTemp: '275',
    wrapMethod: 'No wrap',
    wrapTemp: '',
    targetInternalTemp: '205',
    cookTimeHours: '9',
    cookTimeMinutes: '0',
    restTime: '60',
    weatherTemp: '82',
    weatherHumidity: '70%',
    rating: 9,
    tags: ['tailgate'],
    photos: [],
    notesLog: [],
  },
  {
    id: '__example_friend_cook_3__',
    _isExample: true,
    userName: 'Brother Brian',
    name: 'Backyard Pulled Pork',
    date: '2026-06-01',
    meatType: 'Pulled Pork',
    cut: 'Boston butt, bone-in',
    weight: '8.5',
    rub: 'Brown sugar + paprika + cumin',
    woodType: ['Apple', 'Cherry'],
    smokerType: 'Pit Boss Pro Series',
    fuelSource: 'Pellets',
    cookTemp: '250',
    wrapMethod: 'Foil',
    wrapTemp: '160',
    targetInternalTemp: '203',
    cookTimeHours: '11',
    cookTimeMinutes: '30',
    restTime: '45',
    weatherTemp: '76',
    weatherHumidity: '55%',
    rating: 7,
    tags: ['weekend'],
    photos: [],
    notesLog: [],
  },
  {
    id: '__example_friend_cook_4__',
    _isExample: true,
    userName: 'Dad',
    name: 'Sunday Ribs',
    date: '2026-06-07',
    meatType: 'Ribs',
    cut: 'St. Louis style spare ribs',
    weight: '6',
    rub: 'Kansas City style — sweet + smoky',
    woodType: ['Cherry', 'Pecan'],
    smokerType: 'Weber Smokey Mountain 22',
    fuelSource: 'Charcoal',
    cookTemp: '275',
    wrapMethod: 'Foil',
    wrapTemp: '170',
    targetInternalTemp: '198',
    cookTimeHours: '5',
    cookTimeMinutes: '30',
    restTime: '20',
    weatherTemp: '74',
    weatherHumidity: '60%',
    rating: 8,
    tags: ['family dinner'],
    photos: [],
    notesLog: [],
  },
];

export const SAMPLE_COOK = {
  id: '__example_cook__',
  _isExample: true,
  name: 'Sunday Brisket',
  date: '2026-05-25',
  meatType: 'Brisket',
  cut: 'Whole packer, choice grade',
  weight: '14.5',
  rub: 'Coarse black pepper, kosher salt, garlic powder',
  rubRecipeId: null,
  sauce: '',
  sauceRecipeId: null,
  woodType: ['Oak'],
  smokerType: 'Weber Smokey Mountain 22',
  fuelSource: 'Charcoal',
  cookTemp: '250',
  wrapMethod: 'Butcher paper',
  wrapTemp: '170',
  targetInternalTemp: '203',
  cookTimeHours: '12',
  cookTimeMinutes: '30',
  restTime: '90',
  weatherTemp: '72',
  weatherWind: '5-10 mph gusts',
  weatherHumidity: '55%',
  photos: [],
  notesLog: [
    '5/25/2026 06:15 AM: Trimmed and rubbed last night, on the smoker now. 250F.',
    '5/25/2026 09:30 AM: Bark forming nicely. Spritzed with apple cider vinegar.',
    '5/25/2026 12:00 PM: Hit the stall at 165F. Wrapped in butcher paper.',
    '5/25/2026 03:45 PM: Probe tender at 203F. Pulled and into the cooler to rest.',
    '5/25/2026 05:15 PM: Sliced after 90 min rest. Juicy, great pull-apart texture.',
  ],
  notes: '',
  whatIdChange: 'Start 30 minutes earlier. Could have used another hour of rest. Also try post oak instead of regular oak next time for a slightly sweeter smoke.',
  rating: 8,
  tags: ['weekend', 'family dinner'],
  recipeIds: [],
  shared: false,
  lastEdited: null,
};
